### ISSUE TITLE
Import via csv: wrong behavior when uploading with status = 2 again

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#100]
1.
A status was set to 2 (=archive).
When I upload a file where the row has the status = 2 then it reports a successful archive but the geometry is visible again.
When I upload the file again then it reports a successful archive and the geometry is also archived.
and again and again

2.
A status was set to 2 (=archive).
When I upload a file where the row has status = 2 and I have updates for other columns it should execute these updates. The plotchart admin maybe wants to change info of already archived rows later, e.g. add info to the description.

**Comment by EleonoraPetzold** [comment]
to 1:
Should it be here so that if in the DB already status 2 is the program then does nothing?
Are you sure that the geometry was visible? We use the same archive function for the import as in the ui.

**Comment by aostrow** [comment]
if it has already status 2 then it should do an update (if possible)
yes, I could switch the visibility by uploading the file again and again

**Comment by aostrow** [comment]
I tested it and it seems to work now.
