### ISSUE TITLE
Import via csv: polar coordinates do not work

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#105]
(With the UI it works)

Tried the data from LMTs but the first line with polar coordinates 

`HEW4|679|40396|Core Arthropods - Phytotelm_1|circle|(135, 28.3),1|polar|1|#FFFFFFAA|2009: artificial phythotelm, bucket on a stem|2`

gave this error:

![image](https://user-images.githubusercontent.com/26480843/145428772-64391829-bb9b-4fe1-8013-5249f4e9f9c3.png)

**Comment by EleonoraPetzold** [comment]
Reason for error: ReferencePoint is missing in import/export

**Comment by EleonoraPetzold** [comment]
Test by andreas successful
