### ISSUE TITLE
Typo: in admin panel for plots

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#11]
In pmm/mainAdmin/ in the update "section":
missing "e" in RefrencePoint

**Comment by geofranzi** [comment]
..nicht nur da, sondern auch sehr konsequent durch den gesamten Code hindurch. Kann ich alles gleich mitändern, außer dem Spaltennamen in der Tabelle, den lass ich lieber wie er ist.
