### ISSUE TITLE
Error appears when adding a subplot

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#112]
After a user: "...neuer Plot (Antonios-temporary...Ich kann immer genau einen Subplot anlegen. Beim zweiten kommt dann die Fehlermeldung. Das habe ich jetzt umgangen, indem ich mich nach jedem Subplot aus- und wieder eingeloggt habe."

Error seems a Alert with "(Error: Internal Server Error)."

Should be tested if it can be reproduced.

**Comment by EleonoraPetzold** [comment]
I have rebuilt the scenario on the test server. The creation of the subplots went without problems. The issue is not reproducible.
