### ISSUE TITLE
SOIL subplot, transects along EP edge

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#128]
SOIL subplot, transects along EP edge, Core 7 - Arthropods I overlap the other subplots in the plot. This makes them difficult to read. SOIL should be in the background, the other subplots in front.

**Comment by aostrow** [comment]
wir hatten schonmal was an der reihenfolgder der darstellung gemacht (klein über groß). da ist das wohl mit gelöst worden. wir erkennen keine probleme bei der darstellung
