### ISSUE TITLE
API does not work on prod

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#132]

**Comment by EleonoraPetzold** [comment]
API folder was missing is the VS solution, I think that is the problem. Let's see after next publishing.

**Comment by aostrow** [comment]
It seems to work now.

But I do not know what to enter for: [get](https://www.bexis.uni-jena.de/apihelp/index#!/PlotOut/PlotOut_GetSubplotsGrouped) [/api/Subplot/grouped/{id}](https://www.bexis.uni-jena.de/apihelp/index#!/PlotOut/PlotOut_GetSubplotsGrouped)
