### ISSUE TITLE
Opacity is not added to color in a specific case

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#143]
When editing a line and then removing the color and updating it, the opacity only is stored.
When I re-edit it and chose a color then the opacity is not chosen correctly and a NaN is added to the color. 
Now the plot gives an error if I select it.

**Comment by EleonoraPetzold** [comment]
`<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA01" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA02" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA03" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA04" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA05" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA06" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA07" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA08" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA09" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="AEA10" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA01" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA02" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA03" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA04" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA05" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA06" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA07" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA08" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA09" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="HEA10" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA01" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA02" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA03" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA04" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA05" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA06" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA07" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA08" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA09" /> <Property Name="Value" value="_null_null" /> </Item>
<Item Name="DomainItem" typeid="1"> <Property Name="Key" typeid="2" value="SEA10" /> <Property Name="Value" value="_null_null" /> </Item>`

done on prod

**Comment by EleonoraPetzold** [comment]
Color can't be null, we must ensure that
