### ISSUE TITLE
Former subplots are not shown dotted

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#24]
Former subplots sind nicht gestrichelt.

- [x] checken, ob es noch linetype gibt, dann hier das dotted/dashed einstellen

- [x] wenn nicht, dann sollten wir eine spezielle Farbe zuweisen, Vorschlag: #856f6f

**Comment by geofranzi** [comment]
Es gibt keine Plots, die als "former" gekennzeichnet sind. Der Status ist immer "1" und im Code wird nach "2" geprüft. Die Tabelle pmm_geometryinformationhistory ist auch leer. Sollten die Einträge dort drin sein?

**Comment by aostrow** [comment]
Das wird uns leider nur ein Blick in den Code verraten, also was passiert, wenn man den Archive-Button drückt.
Die History-Tabellen können auch die Logs-Tabellen sein, also die Dokumentation der CRUD (ohne R) an den Plotcharts.

**Comment by aostrow** [comment]
Status = 2 = former Subplots.
Wird momentan nicht bei Migration berücksichtigt.
Wenn repariert, können wir hier weiterschauen, ob noch todo oder erledigt.

**Comment by aostrow** [comment]
wird als dotted angezeigt.
- linetype gibt es nicht mehr in db aber
- im code wird status (former = 2) abgefragt und dann entsprechend gezeichnet
- ging nicht, da bei migration kein status=2 übertragen wurde, siehe #16
