### ISSUE TITLE
Non-sub plot feature

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#38]
There is also the option to create plots, the parents of the subplots we usually use. 
- Where is it in the code?
- Is there an option to create pdfs from this plots? I mean to choose a list of plots and compile all together in a pdf?

**Comment by EleonoraPetzold** [comment]
I added the view for managing plot to the admin menu:

![image](https://user-images.githubusercontent.com/42029171/110085946-0525e980-7d92-11eb-97d8-020b5d5058cf.png)

It is possible to select plots and print it to pdf:

![image](https://user-images.githubusercontent.com/42029171/110086220-6483f980-7d92-11eb-90c5-d1e90dc01ae8.png)

![image](https://user-images.githubusercontent.com/42029171/110086256-6f3e8e80-7d92-11eb-94d4-8ef74d449b1b.png)

**Comment by EleonoraPetzold** [comment]
I think we need to test this view in detail.

**Comment by EleonoraPetzold** [comment]
ist da und wird beim nächsten mal veröffentlicht...
