### ISSUE TITLE
Table with legend does not update

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#39]
Neueingetragene Subplots werden nicht in Tabelle angezeigt.
Auch nicht im Edit Modus. De Manager kann also nicht weiter editieren oder löschen.

**Comment by EleonoraPetzold** [comment]
Die Tabelle hat ein Problem die richtigen subplots anzuzeigen, wenn man " draw beyond plot borders" anklickt ist der subplots zu sehen obwohl er innerhalb des plots liegt.

**Comment by EleonoraPetzold** [comment]
add to issue Geometry types and beyond plot borders #49 and close
