### ISSUE TITLE
Color: no color should be possible (and default)

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#40]
Es scheint, dass beim leeren der Farbe immer der Hexcode #FFFFFF (weiß) mit Transparenz (?) genommen wird. Dadurch sind keine reinen Kreiselinien möglich und unterliegende Subplots werden verdeckt.
Ist "leere" Farbe möglich?
B2
![image](https://user-images.githubusercontent.com/26480843/108911237-4ba77580-7627-11eb-81d8-53b3741fe9a4.png)

B1
![image](https://user-images.githubusercontent.com/26480843/108911497-9a550f80-7627-11eb-94d4-0963688ee507.png)

**Comment by EleonoraPetzold** [comment]
Leere Farbe ist möglich->

**Comment by EleonoraPetzold** [comment]
solved with
`update public.pmm_geometryinformation
set color = 'aa'
WHERE name like '%- Gap'`
