### ISSUE TITLE
Plot border - all plots

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#44]
Plotborders are not drawn for all plots. Please draw that there is no confusion with other subplots.

**Comment by aostrow** [comment]
- info is available in pmm.plots table (geometry type + coordinates)
- width, line type and color needs to be set default (hardcoded or via config)
- do we want in in config: draw border: y/n ?

**Comment by aostrow** [comment]
check #52

**Comment by aostrow** [comment]
Seems that with the current solution the border is hard coded. But we need to read the border info from the database table: pmm.plots (geometry type + coordinates)

----

Check HEG31as example.
![grafik](https://github.com/bexis/Module_ResearchAreaManagement/assets/26480843/f545dc82-decc-41cf-9567-f366142e9796)

**Comment by EleonoraPetzold** [comment]
done and published
