### ISSUE TITLE
Behavior when changing Grid Size

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#53]
Je nach unterschiedlicher Auswahl der "Grid Size" verändert sich die größe des Umfeldes um den Plot. Dadurch wird beispielsweise bei Grid Size "1" der eigentliche Plot sehr klein.
Für alle Darstellungen wäre eine gleiche, geringe Umrandung ausreichend.

**Comment by aostrow** [comment]
grid is fixed
