### ISSUE TITLE
Adapted SharpMap v1.1

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResearchAreaManagement#54]
based on v1.1 (https://github.com/SharpMap/SharpMap/releases/tag/v1.1) + fix from https://github.com/SharpMap/SharpMap/issues/110

[SharpMap.zip](https://github.com/bexis/Module_ResearchAreaManagement/files/6172763/SharpMap.zip)

replace in ....\packages\SharpMap.1.1.0\lib\net40-client

**Comment by geofranzi** [comment]
https://github.com/bexis/SharpMap/commits/V1_1_and_changes

**Comment by aostrow** [comment]
put info with workaround above in readme
