### ISSUE TITLE
Label position and layout

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#63]
- [x] make font smaller
- [x] draw label on the right position on the subplot (chose the right corner depending which coordinate is read from the geometry: e.g. NE corner, SW corner for rectangle)
- [x] draw label more connected to the position (e.g. use middle of font and not top border of the font)

related code should be around here:
https://github.com/bexis/Module_ResearchAreaManagement/blob/9f0a3521da0f1d9822d00bcc636ca44c1ee4ad79/BExIS.Pmm.Model/Plotchart.cs#L641

**Comment by aostrow** [comment]
```
layLabel.Style.VerticalAlignment = SharpMap.Styles.LabelStyle.VerticalAlignmentEnum.Top; (oder bottom)
layLabel.Style.HorizontalAlignment = SharpMap.Styles.LabelStyle.HorizontalAlignmentEnum.Left; (oder right)
```
moves Label just "minor" arounf it position (point od interest), seen from the perspective of the label.


`layLabel.Style.Offset = (new PointF((float)plotLayer.Envelope.MaxX, (float)plotLayer.Envelope.MaxY));`

moves the label based on x/y of the envelope of the underlying coordinates.

**Comment by aostrow** [comment]
rectangle needs something like this:

```
if (xy[0] < xy[2] && xy[1] < xy[3])
newRow["Label"] = xy[2] + "," + xy[3];
left
bottom
maxx
maxy


else if (xy[0] > xy[2] && xy[1] > xy[3])
newRow["Label"] = xy[0] + "," + xy[1];
left
bottom
maxx
maxy


else if (xy[0] > xy[2] && xy[1] < xy[3])
newRow["Label"] = xy[0] + "," + xy[1];
left
top
maxx
miny


else if (xy[0] < xy[2] && xy[1] > xy[3])
newRow["Label"] = xy[2] + "," + xy[3];
left
top
maxx
miny
```
