### ISSUE TITLE
Data migration

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#7]
- [x] write data migration routine plot chart and subplots

- [x] implement special case for experimental plots (exp plots on forest)

- [x] implement special case for 2 plots

**Comment by EleonoraPetzold** [comment]
Error:
PartialEvalException (KeyNotFoundException ("The given key was not present in the dictionary."), value(System.Collections.Generic.Dictionary`2[System.Int32,System.String]).get_Item(7395))

For some geometry ID:
7394
7393
7392
7391
7390
7389
7388
7387
7386
7385
...

- [ ] check why

**Comment by EleonoraPetzold** [comment]
Subplot GeometryText Error:
"Invalid number of points in LineString (found 1 - must be 0 or >= 2)"
linestring(9.30429595062724 48.4928231384685)

**Comment by aostrow** [comment]
special case forest: uploaded extra data into dataset 20907 because it is needed for the data transfer

**Comment by geofranzi** [comment]
`Update pmm_geometryinformation set description = 'since 2008: flight-interception traps; every third year' where description = '"since 2008: flight-interception traps; every third year"'`

Einmal zum Schluß ausführen

**Comment by EleonoraPetzold** [comment]
Auch zum Schluss ausführen um die logs von Bexis1 zu holen:

1. Create table in postgres DB
`CREATE TABLE public.PMM_OLDPLOTCHARTLOG(
       ID integer,
       GEOMETRY_ID integer,
       USERNAME VARCHAR(255),
       DATE TIMESTAMP,
       CHANGES  VARCHAR(255)); 
       TABLESPACE pg_default;
       ALTER TABLE public.PMM_OLDPLOTCHARTLOG OWNER to postgres;`´

2. Export data from DB2 BioDiv
´CALL SYSPROC.ADMIN_CMD( 'EXPORT TO "C:\Users\administrator\Desktop\plotchartLog.txt" OF DEL MODIFIED BY COLDEL| NOCHARDEL MESSAGES ON SERVER 
SELECT ID, GEOMETRY_ID, USERNAME, DATE, REPLACE(REPLACE(changes ,chr(10),'' ''),chr(13),'' '')
 FROM EXPLORER.PLOTCHART_LOG' ); ´´

3. Convert Entcoding to "UTF-8 Without BOM"

4. Import to postgres DB

**Comment by EleonoraPetzold** [comment]
- [ ] add new experimatal plot to domain constraint druing migration
