### ISSUE TITLE
Massiv export of subplots as CSV is needed

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResearchAreaManagement#70]
what: To update the plotchart via file upload an export is needed beforehand. It should be possible to export all (or a self chosen amount) of subplots together with the plot-labels. 

where: In "manage plotchart" currently the CSV export, does provide the geometries for the plot itself. Add another export function: "CSV of underlying subplots".

**Comment by aostrow** [comment]
Plotchart Admin of the BE asks for this export. Would be nice to have it via UI.

"Include underlying subplots" could be a checkbox next to the CSV icon. (After the icons are re-arranged. #81)
Export should contain all subplot exports together with Plot Ids from Main plots.
Selection of individual plots (existing checkboxes in the grid view) currently not needed.

**Comment by EleonoraPetzold** [comment]
export include underlying subplots looks so, now
![image](https://user-images.githubusercontent.com/42029171/120316978-57699e80-c2de-11eb-8245-b8357831a52c.png)
 Ok?

**Comment by aostrow** [comment]
Ok. Das sollten ja alle Infos sein, die benötigt werden, um ein Update machen zu können? Es sind alle veränderbaren Komponenten vertreten? Also auch bspw. Linewidth? 
Kann noch ein Header mitgeliefert werden? Also bspw.:
plotid, internal plotid, subplot id, ...

**Comment by aostrow** [comment]
see #9
