### ISSUE TITLE
Color formats are not displayed right

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResearchAreaManagement#86]
- Navigate to Manage Plots
- Check the color formats 

Result:

HEX color codes additionally have AA or FF at the end.
![err](https://user-images.githubusercontent.com/66725469/128629198-c819b849-1593-48c4-aa50-a36fad1b8d15.png)

**Comment by aostrow** [comment]
This is ok because it is the hexadecimal color code for transparency.
If you agree please close.

**Comment by bayramliaziz** [comment]
> 
> 
> This is ok because it is the hexadecimal color code for transparency.
> If you agree please close.

Thanks for the clarification, I will close the issue.
