### ISSUE TITLE
Download pdf doesn't work properly

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResearchAreaManagement#88]
First:

- Navigate to Manage Plot Charts
- Select a plot and click Download (the download icon beside the gride size field)

Result:
The downloaded pdf file is empty.

Second:

- Navigate to Manage Plot Charts
- Select multiple plots and click Download pdf (the download icon beside the gride size field)

Result: 
If three plots are chosen to be downloaded, there are only two plots present in the downloaded pdf file. It seems when multiple plots are chosen to be downloaded, the first plot is always missing in the pdf file.

**Comment by EleonoraPetzold** [comment]
The problem no longer occurs
