### ISSUE TITLE
Test CSV import

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#9]
Link: http://be2020-dev.inf-bb.uni-jena.de:2010/pmm/MainAdmin/Index

**Notes:**
- if you what to insert a new subplot or plot the ID must be blank
- there will be an update of all rows in the file

- [x] Test functionality 
- [x] check report after upload
- [x] check data 
- [x] check history info

**Comment by geofranzi** [comment]
I have no test data to check.

**Comment by aostrow** [comment]
- **functionality:** 
  - Status seems not to be considered, but it should. Systems set it automatically to 1, also if I enter 2. 

- **report:** 
  - Last column "status" seems to indicate if the upload happened or not. I did a test with a wrong coordinate and the status checkbox was not checked. Rename column, e.g. "Upload successful". Put column on the first place.
  - Is it easy to provide a download (send mail?) of the report?

- **data:**
  - Uploaded data seems ok 
  - Date column for updated data is not changed. Shouldn't it reflect the date of the latest changes? On the other hand we have the date info in the history table.

- **history:**
  - Ok. It writes the new data also in the history table.

**Comment by aostrow** [comment]
I set status = 2 and plot was archived.
I set status = 1 again and in report an update was written but the geometry was still archived.

**Comment by EleonoraPetzold** [comment]
test successful code published on prod server
